/*SELECT 
    *
FROM
    PRODUCTE
*/
/*SELECT *
FROM PRODUCTE
 WHERE DESCRIPCIO LIKE '%TENNIS%'
 */
 /*SELECT CLIENT_COD, NOM, TELEFON, AREA
 FROM CLIENT
  */
 /* SELECT CLIENT_COD, NOM, CIUTAT, TELEFON
  FROM CLIENT
  WHERE AREA NOT LIKE '636'
  */
  /*SELECT CLIENT_COD as CODI, DATA_TRAMESA as DatesTramesa, COM_DATA as Datesorde
  FROM COMANDA
  */
/*SELECT CLIENT_COD, NOM, OBSERVACIONS, LIMIT_CREDIT
FROM CLIENT  
WHERE LIMIT_CREDIT > 4000 and 
	LIMIT_CREDIT < 8000 and
    UPPER(NOM)   LIKE '%S%' 
    */