/*SELECT NOM, HOSPITAL_COD, TELEFON
FROM HOSPITAL
*/
/*SELECT NOM, HOSPITAL_COD, TELEFON
FROM HOSPITAL
WHERE NOM LIKE '_S%'
*/
/*SELECT HOSPITAL_COD, SALA_COD, EMPLEAT_NO, COGNOM
FROM PLANTILLA
*/
/*SELECT HOSPITAL_COD, SALA_COD, EMPLEAT_NO, COGNOM, TORN
FROM PLANTILLA
WHERE TORN NOT LIKE 'N'
*/
/*
SELECT *
FROM MALALT
WHERE 
	year(DATA_NAIX) = 1960
    */
/*SELECT *
FROM MALALT
WHERE 
	year(DATA_NAIX) <='1960%'
*/
/*SELECT HOSPITAL.NOM, HOSPITAL.HOSPITAL_COD, DOCTOR.COGNOM, DOCTOR.HOSPITAL_COD
FROM HOSPITAL, DOCTOR
WHERE HOSPITAL.HOSPITAL_COD = 22 and
		DOCTOR.HOSPITAL_COD = 22
        /*and
DOCTOR.HOSPITAL.COD = HOSPITAL.HOSPITAL_COD;*/